---
chdir: /your/app/directory
port: 4567
environment: production
log: /your/app/directory/log/thin.log
pid: /your/app/directory/tmp/pids/thin.pid
daemonize: true
threaded: true
servers: 1
onebyone: true
max_conns: 1024
max_persistent_conns: 512
